### ISSUE TITLE
Always out of memory

### ISSUE THREAD

**Issue by visonpon** [yunjey/StarGAN#25]
@yunjey As the training continues, the memory it needs increased ,and stopped when   it report the runtimeError said that out of memory.
I don't know why the memory increased all the time as training proceed, and I wonder if i modify the code to use muitl-gpu , whether  i will also  receive the same error or not?
btw, my gpu memory is 12G
thanks~

**Comment by rAm1n** [comment]
Hi @visonpon  
I am not sure if I can help but I tried training on celebA and RafD seperately and memory was stable and always below 5gb. Your gpu memory is even bigger than mine which is 8Gb. So may be check if you have the latest version of the code?

 This increase in memory with pytorch normally happens when people keep handles to a variable from previous iterations.

**Comment by visonpon** [comment]
thanks, i have solved this problem by update my code according to your advice ~
