### ISSUE TITLE
number of parameters

### ISSUE THREAD

**Issue by TonyBMontana** [yunjey/StarGAN#42]
Hello @yunjey , 
Thanks for the great project!
I've noticed, that the total number of parameters doesn't change in accordance with image_size. Why so?

**Comment by yunjey** [comment]
@TonyBMontana In StarGAN, we used the same network architecture for both 128x128 and 256x256 resolutions. However, GPU memory usage for 128x128 resolution is less than 256x256, since the activation maps are reduced by half.

For the network architecture, check the Table 4 and 5 in the [paper](https://arxiv.org/pdf/1711.09020.pdf).
