### ISSUE TITLE
Why the performance is superior to CycleGAN? 

### ISSUE THREAD

**Issue by lrlgg** [yunjey/StarGAN#54]
The architecture of the network are similar to CycleGAN when transform one domain to another domain, but the performance is superior to CycleGAN. The main difference is the using of gradient penalty. Does the gradient penalty  play a great role?

**Comment by yunjey** [comment]
@lrlgg We mentioned possible reasons for StarGAN's superiority in Section 5.4 and 5.5 of the paper. For a fair comparison, we had applied wgan-gp loss to CycleGAN but the results were not visually improved. 

When learning to synthesis face images, it is important for the generator to detect face features (e.g., eyes or hair colors) internally. Instead of learning a fixed translation (e.g, black hair to blond hair), which may prone to overfitting,  StarGAN learns to flexibly translate an input image to the corresponding target domain. We can also interpret StarGAN as multi-task learning version of CycleGAN (learning to translate images from black to blond hair, brown to black hair, and so on).
