### ISSUE TITLE
training strategy of generator

### ISSUE THREAD

**Issue by liangbh6** [yunjey/stargan#69]
from def train_multi(self) in the solver.py in this repository, my understanding is that when training the translation ability, it only involves translation within one dataset(target labels with one) .What about training with target labels across the datasets?

**Comment by yunjey** [comment]
Yes, you can possibly translate celeba images using the rafd labels. In this case, you don’t know about the original label, so that you can not optimize the reconstruction loss, but can optimize the domain classification loss. We did’nt try this strategy, but I think it will improve the visual quality of translation results.
